In [141]:
import numpy as np


# 1. Работа с массивами NumPy
Все упражнения ниже нужно делать без использования циклов Python

1. Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

In [142]:
x1 = np.arange(1 , 21)
X1 = 2**x1 / x1
X1

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

2. Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$

In [143]:
i = np.arange(6)
np.sum(0.1**(3*i) * 0.2**(4*i))  

1.00000160000256


3. Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [144]:
x3 = np.zeros((8,8))
x3[1::2, ::2] = 1
x3[::2, 1::2] = 1
x3

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

4. Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [145]:
X4 = np.random.random((5, 2))


x = np.sqrt(X4[:, 0]**2 + X4[:, 1]**2)
y = np.arctan2(X4[:, 1], X4[:, 0])

x, y

(array([0.97086918, 0.3773458 , 0.92396938, 0.39883422, 0.61934352]),
 array([1.16251083, 0.73473071, 0.59580801, 1.33326147, 0.60467188]))

5. Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

In [146]:
X5 = np.random.random((10, 10))

ans = np.unravel_index(np.argmax(X5), X5.shape)
ans

(1, 9)

6. Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [147]:
X6 = np.random.random((10, 2))
y6 = np.random.random((1, 2))
distance = ((X6[:, 0] - y6[:, 0]) ** 2 + (X6[:, 0] - y6[:, 1]) ** 2)**0.5
X6[np.argmin(distance)]

array([0.51444754, 0.37730091])

7. Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, &amp; x &lt; 0  \\
    x + 6, &amp; 0 \le x \le 2 \\
    x^2 + 4x - 4, &amp; x \ge 2
 \end{cases}
$$
Постройте массив из её значений на $-3 \le x \le 3$.

In [148]:
step = 0.5 
X7_1_x = np.arange(-3 , 0 , step)
X7_2_x = np.arange(0 , 2 , step) 
X7_3_x = np.arange(2 , 3.5 , step)

X7_1_y = map(lambda x: x**2 + 2*x + 6 , X7_1_x)
X7_2_y = map(lambda x: x + 6 , X7_2_x)
X7_3_y = map(lambda x: x**2 + 4*x - 4 , X7_3_x)

ans7 = np.hstack((list(X7_1_y) , list(X7_2_y) , list(X7_3_y)))
ans7

array([ 9.  ,  7.25,  6.  ,  5.25,  5.  ,  5.25,  6.  ,  6.5 ,  7.  ,
        7.5 ,  8.  , 12.25, 17.  ])

8. Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

In [149]:
X8 = np.random.random((10, 10))

X8 = X8.T - np.mean(X8, axis=1).T
X8 = X8.T

np.mean(X8, axis=1)

array([ 0.00000000e+00, -7.77156117e-17, -5.55111512e-17,  4.44089210e-17,
       -3.33066907e-17, -1.11022302e-17, -2.22044605e-17,  3.33066907e-17,
       -3.33066907e-17, -2.22044605e-17])


9. Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию.

In [150]:
X9 = np.random.normal(loc=5, scale=2., size=1000)
mean = X9.mean()
var = X9.var()
mean, var

(4.984236170360262, 3.8043208635663004)

10. Создать матрицу:

$$
\begin{pmatrix}
0 &amp; 1 &amp; 2 &amp; 3 &amp; 4 \\
1 &amp; 2 &amp; 3 &amp; 4 &amp; 0 \\
2 &amp; 3 &amp; 4 &amp; 0 &amp; 1 \\
3 &amp; 4 &amp; 0 &amp; 1 &amp; 2 \\
4 &amp; 0 &amp; 1 &amp; 2 &amp; 3
\end{pmatrix}
$$

In [151]:
## your code
X10 = np.ones((5, 5)) * np.arange(5)
X10 += X10.T
X10 %= 5
X10

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 0.],
       [2., 3., 4., 0., 1.],
       [3., 4., 0., 1., 2.],
       [4., 0., 1., 2., 3.]])

11. Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [152]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)

[0, 1, 0, 0, 4]

In [153]:
def better_sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    partial = np.repeat(np.cumsum(x), c).reshape((len(x), c)).astype("float32")
    val = s * np.random.random(c)
    partial -= val.T
    partial[partial >= 0] = 0
    
    return np.argmax(partial, axis=0)

better_sample([50, 3, 1, 7, 20], 5)

array([4, 3, 0, 0, 3], dtype=int64)